### ISSUE TITLE
语言问题

### ISSUE THREAD

**Issue by dreamkily** [huangleiBuaa/OthogonalWN#3]
您好，我最近在做基于迁移学习方面的工作，有一部分想借鉴下您的这篇论文关于正交方面的想法，但是您的lua代码我看的不是很懂，请问您有pytorch版本的代码吗，非常感谢。^_^
@huangleiBuaa

**Comment by huangleiBuaa** [comment]
@dreamkily 
Hi， I have updated the pytorch module of OWN in this project. Please refer to it.

**Comment by dreamkily** [comment]
thank you very much
